### ISSUE TITLE
Generate only directed acyclic graphs

### ISSUE THREAD

**Issue by thedrow** [pckroon/hypothesis-networkx#10]
Is there a way to do so without filtering?

**Comment by pckroon** [comment]
Interesting question :)
The directed part is easy (`graph_type=nx.DiGraph`).
For the acyclic part: Could you try with `max_edges=0, connected=True`? The algorithm won't make (undirected) cycles in the first phase, and uses any "leftover" edges to create possibly cyclic edges later. However, this will greatly limit the type of graphs you'll get. I would try filtering/assuming first, since I don't really expect too many cyclic directed graphs.

**Comment by thedrow** [comment]
But won't `max_edges=0` mean there won't be any edges to any node?

**Comment by pckroon** [comment]
No, that constraint will be violated to ensure the graph is (weakly) connected.

**Comment by thedrow** [comment]
Well it makes my test run forever since sometimes there are too many nodes.

**Comment by pckroon** [comment]
It scales poorly with the number of nodes (at least N^2)
From the readme:
> Graph generation may be slow for large graphs.

**Comment by thedrow** [comment]
Nah it's my test that is slow, not the graph generation itself.

**Comment by pckroon** [comment]
Unless there's anything further on generating DAGs I'll close the issue. Feel free to reopen it if it's not resolved.
